---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64 # 16.04
  - name: ubuntu/trusty64 # 14.04
  - name: centos/7        # 7
  - name: centos/6        # 6
  - name: debian/jessie64 # 8
  - name: debian/wheezy64 # 7

suites:
  - name: default
    run_list:
    - recipe[cop_tls::dhparams]
    - recipe[cop_tls::snakeoil]
    - recipe[cop_nginx::default]
    attributes:
        tls:
            snakeoil:
                certs:
                    test.localhost.com:
                        country: US
                        state: Oregon
                        city: Portland
                        company: Copious
                        section: Devops
                        hostname: test.localhost.com
                        contact: test@copiousdev.com
        nginx:
            remove_default_site: true
            vhosts:
               test.localhost.com:
                   server_name: test.localhost.com
                   additional_names: something.test.localhost.com
                   docroot: /var/www/html/testing
                   ssl:
                       cert: /etc/ssl/certs/test.localhost.com.crt
                       key: /etc/ssl/private/test.localhost.com.key
                       dhparams: /etc/ssl/certs/dhparams.pem
                   includes:
                       - compression
                   blocks:
                       - string_block
                       - hashed_block
            blocks:
              string_block:
                content: "# Some nice NGINX code"
              hashed_block:
                content:
                  - "# This"
                  - "# works"
                  - "# too"
  - name: varnish
    run_list:
    - recipe[cop_base::default]
    - recipe[cop_ntp::default]
    - recipe[cop_tls::dhparams]
    - recipe[cop_tls::snakeoil]
    - recipe[cop_varnish::default]
    - recipe[cop_nginx::default]
    attributes:
        tls:
            snakeoil:
                certs:
                    varnish.localhost.com:
                        country: US
                        state: Oregon
                        city: Portland
                        company: Copious
                        section: Varnish
                        hostname: varnish.localhost.com
                        contact: varnish@copiousdev.com
        nginx:
            remove_default_site: true
            vhosts:
               varnish.localhost.com:
                   server_name: varnish.localhost.com
                   docroot: /var/www/html/testing
                   ssl:
                       cert: /etc/ssl/certs/varnish.localhost.com.crt
                       key: /etc/ssl/private/varnish.localhost.com.key
                       dhparams: /etc/ssl/certs/dhparams.pem
        varnish:
          frontend:
            port: 6081
