---
driver:
  name: vagrant
  ssh:
    username: vagrant
    password: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.10.24

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1
    driver:
      box: centos-7.1
      box_url: https://s3.amazonaws.com/copiousdev/vagrant/centos7-ham-packaged.box

suites:
  - name: default
    run_list:
      - recipe[cop_nginx::default]
